before_script:
- rustc --version && cargo --version

image: rust:1.45

test:
  script:
  - cargo test --all-features --verbose

clippy:
  script:
  - rustup component add clippy
  - cargo clippy --verbose

rustfmt:
  script:
  - rustup component add rustfmt
  - cargo fmt -- --check

pages:
  stage: deploy
  script:
  - cargo doc --all-features
  - mv target/doc public
  - |
    echo "
      <!DOCTYPE html>
      <title>Redirection page</title>
      <meta http-equiv=refresh content='0; url=showdown/'>
      <p> Please check out <a href='showdown/'>showdown</a> documentation.
    " > public/index.html
  artifacts:
    paths:
    - public
  only:
  - master
