before_script:
- apt-get update -y
- apt-get install build-essential curl libssl-dev pkg-config -y
- curl https://sh.rustup.rs | sh -s -- -y --default-toolchain nightly-2019-02-26
- PATH=~/.cargo/bin:$PATH
- rustc --version && cargo --version

image: ubuntu:latest

test:nightly:
  script:
  - cargo test --verbose

clippy:
  script:
  - rustup component add clippy-preview
  - cargo clippy --verbose

rustfmt:
  script:
  - rustup component add rustfmt-preview
  - cargo fmt -- --check

pages:
  stage: deploy
  script:
  - cargo doc --all-features
  - mv target/doc public
  - |
    echo "
      <!DOCTYPE html>
      <title>Redirection page</title>
      <meta http-equiv=refresh content='0; url=showdown/'>
      <p> Please check out <a href='showdown/'>showdown</a> documentation.
    " > public/index.html
  artifacts:
    paths:
    - public
  only:
  - master
