test:nightly:
  script:
  - &print_version rustc --version && cargo --version
  - cargo test --verbose
  image: rustlang/rust:nightly

clippy:
  script:
  - *print_version
  - rustup component add clippy-preview
  - cargo clippy --verbose
  image: rustlang/rust:nightly

rustfmt:
  script:
  - *print_version
  - rustup component add rustfmt-preview
  - cargo fmt -- --check
  image: rustlang/rust:nightly

pages:
  stage: deploy
  script:
  - *print_version
  - cargo doc --all-features
  - mv target/doc public
  - |
    echo "
      <!DOCTYPE html>
      <title>Redirection page</title>
      <meta http-equiv=refresh content='0; url=showdown/'>
      <p> Please check out <a href='showdown/'>showdown</a> documentation.
    " > public/index.html
  artifacts:
    paths:
    - public
  image: rustlang/rust:nightly
  only:
  - master
