test:nightly:
  script:
  - &print_version rustup update && rustc --version && cargo --version
  - cargo test --all --verbose
  - cd enum-map
  - cargo test --all-features --verbose
  image: rust-lang/rust:nightly

clippy:
  script:
  - *print_version
  - rustup component add clippy-preview
  - cargo clippy --verbose
  image: liuchong/rustup:nightly

rustfmt:
  script:
  - *print_version
  - rustup component add rustfmt-preview
  - cargo fmt -- --check
  image: liuchong/rustup:nightly
