[package]
name = "showdown"
version = "0.1.0"
authors = ["Konrad Borowski <konrad@borowski.pw>"]
edition = "2018"

[dependencies]
chrono = "0.4.6"
futures = "0.1.25"
futures03 = {package = "futures-preview", version = "=0.3.0-alpha.12", features = ["compat"]}
reqwest = "0.9.8"
serde = "1.0.84"
serde_derive = "1.0.84"
serde_json = "1.0.35"
tokio = {version = "0.1.14", features = ["async-await-preview"]}
websocket = {version = "0.22.1", default-features = false, features = ["async", "async-ssl"]}

[dev-dependencies]
comparator = "0.1.1"
rand = "0.6.4"
