[package]
name = "showdown"
version = "0.3.1"
authors = ["Konrad Borowski <konrad@borowski.pw>"]
description = "Pokemon Showdown Client"
license = "MIT/Apache-2.0"
repository = "https://gitlab.com/KonradBorowski/showdown"
edition = "2018"

[dependencies]
chrono = "0.4.6"
futures = "0.3.5"
rental = "0.5.2"
reqwest = { version = "0.10.4", features = [ "json" ] }
serde = "1.0.84"
serde_derive = "1.0.84"
serde_json = "1.0.35"
tokio = "0.2.20"
tokio-tungstenite = "0.10.1"
url = "2.1.1"

[dev-dependencies]
comparator = "0.2.0"
rand = "0.6.4"
tokio = { version = "0.2.20", features = [ "macros" ] }
